<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net45;netstandard1.3;netstandard2.0;</TargetFrameworks>
    <AssemblyName>Featureflow</AssemblyName>
    <RootNamespace>Featureflow.Client</RootNamespace>
    <PackageId>Featureflow</PackageId>
    <PackOnBuild>true</PackOnBuild>
    <Authors>featureflow</Authors>
    <Description>Featureflow dotnet client API allows you to add runtime feature management and rollout control to your .net application. Find out more at www.featureflow.io and docs.featureflow.io</Description>
    <Owners>Featureflow</Owners>
    <Title>Featureflow .net client</Title>
    <PackageIcon>icon.png</PackageIcon>
    <PackageLicenseExpression>Apache-2.0</PackageLicenseExpression>
    <PackageProjectUrl>https://www.featureflow.io</PackageProjectUrl>
    <RepositoryUrl>https://github.com/featureflow/featureflow-dotnet-client</RepositoryUrl>
    <Summary>The DotNet Client for Featureflow runtime feature management</Summary>
    <PackageTags>Features Feature Management Release Dark launch Feature Toggles</PackageTags>
    <PackageVersion>1.2.0</PackageVersion>
    <PackageReadmeFile>README.md</PackageReadmeFile>
  </PropertyGroup>
  <ItemGroup>
    <Compile Remove="FeatureflowLogger.cs" />
    <None Include="..\README.md" Pack="true" PackagePath="\" />
    <None Include="icon.png" Pack="true" PackagePath="\" />
  </ItemGroup>
  <ItemGroup Condition="'$(TargetFramework)' == 'net45'">
    <PackageReference Include="System.Net.Http">
      <Version>4.3.4</Version>
    </PackageReference>
  </ItemGroup>
  <ItemGroup Condition="'$(TargetFramework)' == 'netstandard1.3'">
    <PackageReference Include="System.Net.Http">
      <Version>4.3.4</Version>
    </PackageReference>
  </ItemGroup>
  <ItemGroup Condition="'$(TargetFramework)' == 'netstandard2.0'">
    <PackageReference Include="System.Net.Http">
      <Version>4.3.4</Version>
    </PackageReference>
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.1" />
  </ItemGroup>
</Project>